rdi-installer: implement search for raw images

diff --git a/scripts/rdi-installer.sh.in b/scripts/rdi-installer.sh.in
--- a/scripts/rdi-installer.sh.in
+++ b/scripts/rdi-installer.sh.in
@@ -16,9 +16,32 @@ COLOR_TITLE=$COLOR_BLUE
 COLOR_TEXT=$COLOR_BLUE
 COLOR_WARNING=$COLOR_RED
 
-CURSOR="→"
+CURSOR="‣" # "→"
 
 VERSION=@VERSION@
+
+TEMP_DIR=$(mktemp -d)
+
+cleanup()
+{
+    local DIRECTORIES
+    local exit_code=$?
+
+    if [ -d "${TEMP_DIR}/mounts" ]; then
+	DIRECTORIES=$(/bin/ls -d "${TEMP_DIR}/mounts/")
+	for dir in $DIRECTORIES; do
+	    umount -R -f "$dir" || echo "WARNING: Failed to unmount $dir"
+	done
+    fi
+
+    if [[ -d "$TEMP_DIR" ]]; then
+        rm -rf "$TEMP_DIR"
+    fi
+
+    exit $exit_code
+}
+
+trap cleanup EXIT
 
 if [ -z "$RDII_DEBUG" ]; then
     KEYWAIT=keywait
@@ -106,7 +129,7 @@ while [ "$SELECTED" != "Install" ] && [ "$SELECTED" != "Abort" ] && [ -n "$SELEC
 		   --limit=1 \
 		   "Select Keymap ($DEFAULT_KEYMAP)" \
 		   "Select Target Device ($TARGET_DEVICE)" \
-		   "Select Image ($(basename "$SOURCE_IMAGE"))" \
+		   "Select Image ($SOURCE_IMAGE)" \
 		   "Abort" \
 		   "Install"
 	    )
@@ -164,7 +187,7 @@ clear_and_print_title
 
 if gum confirm \
        --default \
-       --prompt.foreground "$COLOR_TEXT" \
+       --prompt.foreground "$COLOR_WARNING" \
        --selected.background "$COLOR_WARNING" \
        --selected.foreground "$COLOR_FOREGROUND" \
        --unselected.background "$COLOR_BACKGROUND" \
@@ -177,8 +200,9 @@ if gum confirm \
     fi
 
 if [ -z "$RDII_DEBUG" ]; then
+    # XXX curl -L -C - --fail --retry 5 --no-progress-meter "https://download.opensuse.org/repositories/home:/kukuk:/mkosi-images/mkosi/raw-disk-image-installer-6.4.x86-64.efi" | dd of=tmp.img bs=4M status=progress conv=fsync oflag=direct
     # Write the image
-    if ! dd if="$SOURCE_IMAGE" of="$TARGET_DEVICE" bs=4M status=progress conv=fsync oflag=direct ; then
+    if ! pv "$SOURCE_IMAGE" | dd of="$TARGET_DEVICE" bs=4M conv=fsync oflag=direct ; then
 	$KEYWAIT -s 0
     else
 	$KEYWAIT -s 10
